apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
<<<<<<< HEAD
        - name: front-end
          image: cyldecryo/parcial1-front-end:10c9e4fa0e9117c5d37bd3c590d266c627336063
=======
        - name: react-container
          image: cyldecryo/parcial1-front-end:6812ec2fed2fe85aa0bf600ea4be01ed2e903147
>>>>>>> 68cc402ecbee565bdbe26e10c7f5c8f32a239899
          ports:
            - containerPort: 80
