apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: back-end
spec:
  selector:
    app: front-end
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30170
