apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: cyldecryo/parcial1-front-end:296ecd931ed5f889e7a0d3a6c57838cb803d715b
          ports:
            - containerPort: 80
