apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app  
  template:
    metadata:
      labels:
        app: react-app  
    spec:
      containers:
        - name: react-container
          image: cyldecryo/parcial1-front-end:2fd815188abbf1b4d942c277aa0d81f90bda0506
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: back-end
spec:
  selector:
    app: react-app  
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30170
  template:
    spec:
      containers:
        - image: cyldecryo/parcial1-front-end:2fd815188abbf1b4d942c277aa0d81f90bda0506
