apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: react-container
          image: cyldecryo/parcial1-front-end:08b4b0703474fa0efccbfe16c8c77319d80df64e
          ports:
            - containerPort: 80
